### ISSUE TITLE
Is there a way to keep some {{args}} after server side renderding?

### ISSUE THREAD

**Issue by butaixianran** [MoLow/ng-node-compile#1]
I still have some angular function need to run at client side, which means, after server side rendering, I still need some {{args}} in html.

For example, an input field or a chat system at client side.
##### This is what we did with other server side template:

We config those server side template, replace {{}} into [[]], so, after server side rendering, all [[...]] are rendered into html, and all {{...}} are still there, then we can use it with client side angular together.

Is there a way to do this with ng-node-compile? Or, is there any solution I can keep some {{args}} after server side rendering?

Thanks!

Btw, this package is great, it gonna save a lot of people's life, as long as people can find this package.

Thanks for this great work.

**Comment by MoLow** [comment]
I guess it shold be no problem to use the $interpolate start&end symbole functions. hope to get to change it somtime

**Comment by MoLow** [comment]
just committed a fix to support that. uploaded it to npm to.
the use is this way:

```
var ngEnviorment = new ngcompile({ startSymbol: '[[', endSymbol: ']]' });
```

did not yet add it to README, so if you have time to contribute to readme it would be very helpfull. otherwise I will do it later.

Mo@Low.

**Comment by butaixianran** [comment]
Thanks, this is great, but first of all, I need to make this package work...
