### ISSUE TITLE
Version of jsdom

### ISSUE THREAD

**Issue by kranthitech** [MoLow/ng-node-compile#5]
ng-node-compile uses jsdom: 5.0.0

When we try to run an application using this modue, we get an error saying jsdom runs only on io.js for versions >4.0

But the current version of jsdom is around 7.0 which does not give this error. Hope you can fix this.

Thanks.

**Comment by MoLow** [comment]
You could use the 1.x version, which works great with node.js instead of io:
https://github.com/MoLow/ng-node-compile/releases
