### ISSUE TITLE
cheerio

### ISSUE THREAD

**Issue by anhoev** [MoLow/ng-node-compile#6]
Hi , can you use cheerio instead of jsdom because it is very fast .

**Comment by MoLow** [comment]
Hi, unfortunately angular is full of native js code, like:

``` javascript
document.createComment(' end ngIf: ' + $attr.ngIf + ' ')
return element[0].nodeType === NODE_TYPE_TEXT ? lowercase(elemHtml)
element.setAttribute(name, value);
```

and lots of other examples..
it is an option to rewrite a version of angular.js that supports server rendering, although, I want to let user select angular version, because new versions keep being published
